"""Emit the warehouse DDL.

    python -m secops_ingest.schema | psql "$DSN"
    python -m secops_ingest.schema --target wazuh_alerts --partitions-ahead 6

Writes SQL to stdout and never connects to a database. Review it, pipe it, or
hand it to whatever applies migrations here -- the point is that the schema is
readable and portable rather than locked inside one deployment tool.

Everything is derived from the transform targets, which already know their raw
table, their fact table and how to create both. Connector modules are not
imported, so this works with no optional dependency installed.
"""

from __future__ import annotations

import argparse
import sys

from ..transform.targets import TARGETS
from . import control_sql, mart_partition_sql, partitions_sql, raw_table_sql


def _banner(text: str) -> str:
    return f"\n-- {'=' * 72}\n-- {text}\n-- {'=' * 72}\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="secops_ingest.schema")
    parser.add_argument(
        "--target", action="append", metavar="NAME",
        help="target to emit DDL for; repeatable. Default: all.",
    )
    parser.add_argument("--partitions-behind", type=int, default=1)
    parser.add_argument("--partitions-ahead", type=int, default=3)
    parser.add_argument(
        "--gin", action="store_true",
        help="index raw JSONB payloads. Write-amplifying; only worth it if raw "
             "is queried ad hoc.",
    )
    parser.add_argument(
        "--no-control", action="store_true", help="skip the control schema"
    )
    args = parser.parse_args(argv)

    names = args.target or sorted(TARGETS)
    unknown = [n for n in names if n not in TARGETS]
    if unknown:
        parser.error(f"unknown target(s): {', '.join(unknown)}. Known: {', '.join(sorted(TARGETS))}")

    out: list[str] = [
        "-- Generated by `python -m secops_ingest.schema`. Idempotent: every",
        "-- statement is IF NOT EXISTS or a guarded DO block, so re-running is safe.",
    ]

    if not args.no_control:
        out.append(_banner("control — run history, watermarks, coverage ledger"))
        out.append(control_sql())

    for name in names:
        t = TARGETS[name]
        out.append(_banner(f"{name}"))

        schema, _, table = t.raw_table.partition(".")
        if not table:
            print(f"target {name}: raw_table {t.raw_table!r} is not schema-qualified",
                  file=sys.stderr)
            return 1

        out.append(f"-- raw landing table\n{raw_table_sql(schema, table, gin_index=args.gin)}")
        out.append(
            f"-- monthly partitions for {t.raw_table}\n"
            + partitions_sql(schema, table,
                             behind=args.partitions_behind, ahead=args.partitions_ahead)
        )

        if t.fact_ddl:
            out.append(f"-- reporting facts\n{t.fact_ddl.strip()}\n")
            # Only partition what declares itself partitioned; a DO block against
            # an unpartitioned table fails, and would fail on every deploy.
            if "PARTITION BY RANGE" in t.fact_ddl:
                out.append(
                    f"-- monthly partitions for {t.fact_table}\n"
                    + mart_partition_sql(t.fact_table,
                                         behind=args.partitions_behind,
                                         ahead=args.partitions_ahead)
                )

        if t.rollup_ddl:
            out.append(f"-- daily rollup\n{t.rollup_ddl.strip()}\n")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
